version: '3'

networks:
  net:

volumes:
  rancher:
  registry:
  nginx-certs:
  nginx-html:
  nginx-vhost:

services:
  registry:
    image: registry:2
    restart: unless-stopped
    networks:
      - net
    volumes:
      - registry:/var/lib/registry
      - registry:/auth
      - registry:/certs
      - nginx-vhost:/etc/nginx/vhost.d:rw
    environment:
      VIRTUAL_HOST: r.secretpool.org
      LETSENCRYPT_HOST: r.secretpool.org
      LETSENCRYPT_EMAIL: admin@secretpool.org
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd

  nginx:
    image: jwilder/nginx-proxy:latest
    restart: unless-stopped
    networks:
      - net
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-html:/usr/share/nginx/html
      - nginx-vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: unless-stopped
    networks:
      - net
    volumes:
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-html:/usr/share/nginx/html:rw
      - nginx-vhost:/etc/nginx/vhost.d:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    image: rancher/server:preview
    restart: unless-stopped
    networks:
      - net
    expose:
      - '443/tcp'
    environment:
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      VIRTUAL_HOST: rancher.secretpool.org
      LETSENCRYPT_HOST: rancher.secretpool.org
      LETSENCRYPT_EMAIL: admin@secretpool.org
    volumes:
      - rancher:/var/lib/mysql:rw
