registry:
  image: registry:2
  restart: always
  volumes:
    - /opt/docker-registry/data:/var/lib/registry
    - /opt/docker-registry/auth:/auth
    - /opt/docker-registry/certs:/certs
  environment:
    VIRTUAL_HOST: registry.secretpool.org
    LETSENCRYPT_HOST: registry.secretpool.org
    LETSENCRYPT_EMAIL: admin@secretpool.org
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd

nginx:
  image: jwilder/nginx-proxy:latest
  restart: always
  ports:
   - '80:80'
   - '443:443'
  volumes:
    - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:ro'
    - '/etc/nginx/vhost.d'
    - '/usr/share/nginx/html'
    - '/var/run/docker.sock:/tmp/docker.sock:ro'

letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion:latest
  restart: always
  volumes_from:
    - nginx
  volumes:
    - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:rw'
    - '/var/run/docker.sock:/var/run/docker.sock:ro'

server:
  image: rancher/server:preview
  restart: always
  environment:
    VIRTUAL_PORT: 8080
    VIRTUAL_HOST: rancher.secretpool.org
    LETSENCRYPT_HOST: rancher.secretpool.org
    LETSENCRYPT_EMAIL: admin@secretpool.org
  volumes:
    - '/home/docker/rancher-server/mysql:/var/lib/mysql:rw'
